name: Daily Commit

on:
  schedule:
    - cron: '49 23 * * *'  

jobs:
  daily_commit:
    runs-on: ubuntu-latest

    steps:

     - name: premakumari.sathiamurthy@straive.com
       run: echo "Hiii  sda"
